Remove_social_spy_on_logout: false
Console_is_social_spy: true
messages:
    format:
        sender: '&7You -> %receiver%: %message%'
        receiver: '&7%sender% -> you: %message%'
        socialspy: '&7%sender% -> %receiver%: %message%'
    notFound:
        general: '&c%reciever% is not online!'
        reply: '&cYou do not have someone to reply to! Are they online?'
    error:
        noTarget: '&cPlease specify a player!'
        noMessage: '&cPlease write a message!'
        sentToSelf: '&cYou can not send a message to yourself!'
    socialspy:
        activated: '&7Social spy mode: &6ON'
        deactivated: '&7Social spy mode: &6OFF'
        prefix: '&7[socialspy] '
    reload: '&aZMessages config reloaded.'
