Remove_social_spy_on_logout: false
messages:
    format:
        sender: '&8You -> %reciever%: %message%'
        reciever: '&8%sender% -> you: %message%'
        socialspy: '&8%sender% -> %reciever%: %message%'
    notFound:
        general: '&c%reciever% is not online!'
        reply: '&cYou do not have someone to reply to! Are they online?'
    error:
        noTarget: '&cPlease specify a player!'
        noMessage: '&cPlease write a message!'
        sentToSelf: '&cYou can not send a message to yourself!'
    socialspy:
        activated: '&aYou are now in social spy mode'
        deactivated: '&bYou are no longer in social spy mode'
        prefix: '&8[socialspy] '
