Remove_social_spy_on_logout: false
messages:
    format:
        sender: '&8You -> %reciever%: %message%'
        reciever: '&8%reciever% -> you: %message%'
        socialspy: '&8%sender% -> %reciever%: %message%'
    notFound:
        general: '&c%reciever% is not online!'
        reply: '&cYou do not have someone to reply to! Are they online?'
    error:
        noTarget: '&cPlease specify a player!'
